"""Chinese labels for stable result-table fields; original source data is unchanged."""

COLUMN_NAMES = {'metric_id': '指标',
 'metric_name': '指标名称',
 'current_value': '当前值',
 'baseline_value': '基准值',
 'absolute_change': '绝对变化',
 'relative_change': '相对变化',
 'current_period': '当前周期',
 'baseline_period': '基准周期',
 'sample_size': '样本量',
 'unit': '单位',
 'direction': '变化方向',
 'severity': '异常等级',
 'z_score': '标准分',
 'confidence_note': '数据完整性',
 'date': '日期',
 'actual_value': '实际值',
 'expected_value': '预期值',
 'lower_bound': '下界',
 'upper_bound': '上界',
 'deviation': '偏差',
 'deviation_pct': '偏差比例',
 'method': '计算方法',
 'stage_name': '漏斗阶段',
 'current_count': '当前数量',
 'baseline_count': '基准数量',
 'current_rate': '当前转化率',
 'baseline_rate': '基准转化率',
 'rate_change_pp': '转化率变化百分点',
 'estimated_order_impact': '估算订单影响',
 'contribution_pct': '贡献占比',
 'dimension': '贡献维度',
 'dimension_value': '维度取值',
 'contribution_value': '贡献值',
 'rank': '排序',
 'confidence_flag': '置信提示',
 'evidence_id': '证据编号',
 'claim': '证据结论',
 'metric': '关联指标',
 'result_table': '来源结果表',
 'supporting_values': '支持数值',
 'confidence': '置信度',
 'caveat': '限制',
 'priority': '优先级',
 'action': '建议',
 'reason': '依据',
 'supporting_evidence_ids': '支持证据',
 'suggested_owner': '建议负责方',
 'verification_metric': '验证指标',
 'expected_direction': '预期方向',
 'limitation': '建议限制',
 'table': '数据表',
 'row_count': '行数',
 'missing_values': '缺失值数量',
 'duplicate_rows': '重复行数量',
 'status': '检查状态',
 'control_group': '对照组',
 'treatment_group': '实验组',
 'control_value': '对照组指标值',
 'treatment_value': '实验组指标值',
 'control_sample_size': '对照组样本量',
 'treatment_sample_size': '实验组样本量',
 'total_sample_size': '总样本量',
 'absolute_lift': '绝对 lift',
 'relative_lift': '相对 lift',
 'p_value': 'p-value',
 'confidence_interval_lower': '置信区间下界',
 'confidence_interval_upper': '置信区间上界',
 'confidence_level': '置信水平',
 'is_significant': '统计显著',
 'significance_conclusion': '显著性结论',
 'statistical_unit': '统计单位',
 'randomization_unit': '随机化单位',
 'confidence_interval_kind': '置信区间类型',
 'ci_unit': '区间单位',
 'stage_id': '阶段标识',
 'net_change_contribution': '净变化贡献率',
 'decomposition_order': '替换顺序',
 'residual_error': '剩余误差',
 'evidence': '异常依据',
 'limitations': '限制说明',
 'metric_type': '指标类型',
 'column_count': '字段数'}


DISPLAY_VALUES = {
    "severity": {"HIGH": "高风险", "MEDIUM": "需要关注", "LOW": "正常波动", "low": "低", "high": "高"},
    "status": {"PASS": "通过", "WARN": "需要关注", "FAIL": "未通过"},
    "confidence": {"high": "高", "medium": "中", "low": "低"},
    "direction": {"increase": "上升", "decrease": "下降", "stable": "稳定", "up": "上升", "down": "下降"},
    "control_group": {"control": "对照组"}, "treatment_group": {"treatment": "实验组"},
    "statistical_unit": {"user_id": "用户（user_id）", "customer_id": "客户（customer_id）"},
    "metric_type": {"mean": "连续型均值", "binary": "二元结果", "proportion": "二元比例"},
}


def localize_result_value(value, column):
    if isinstance(value, str):
        return DISPLAY_VALUES.get(str(column), {}).get(value, value)
    return value
