"""Built-in playbook definitions."""

from __future__ import annotations

from insightpilot.playbooks.models import AnalysisParameter, AnalysisPlaybook, PlaybookRequirements


def _parameter(
    name: str,
    display_name: str,
    parameter_type: str,
    *,
    required: bool = False,
    default: object | None = None,
    choices: list[object] | None = None,
    description: str = "",
) -> AnalysisParameter:
    return AnalysisParameter(
        name=name,
        display_name=display_name,
        parameter_type=parameter_type,
        required=required,
        default=default,
        choices=choices or [],
        description=description,
    )


BUILTIN_PLAYBOOKS: list[AnalysisPlaybook] = [
    AnalysisPlaybook(
        playbook_id="data_profile",
        display_name="数据概览与质量检查",
        description="检查表规模、字段类型、缺失率、唯一值、数值分布和重复行。",
        supported_goal_modes=["periodic_report", "metric_diagnosis", "growth_trend"],
        requirements=PlaybookRequirements(requires_table=True),
        parameters=[_parameter("high_missing_threshold", "高缺失阈值", "float", default=0.5)],
        executor_name="execute_data_profile",
        chart_types=["missingness_bar", "histogram"],
        output_sections=["profile", "quality", "numeric_summary"],
        tags=["profile", "quality"],
    ),
    AnalysisPlaybook(
        playbook_id="metric_trend",
        display_name="指标趋势分析",
        description="按日、周或月聚合指标，计算环比、滚动均值并标记异常点。",
        supported_goal_modes=["growth_trend", "metric_diagnosis", "periodic_report"],
        requirements=PlaybookRequirements(requires_date_column=True, requires_metric_columns=True),
        parameters=[
            _parameter("date_range", "日期范围", "date_range"),
            _parameter("time_grain", "时间粒度", "choice", default="day", choices=["day", "week", "month"]),
            _parameter("aggregation", "聚合方式", "choice", default="sum", choices=["sum", "mean", "count", "min", "max"]),
            _parameter("rolling_window", "滚动窗口", "integer", default=7),
            _parameter("anomaly_threshold", "异常阈值", "float", default=2.0),
        ],
        executor_name="execute_metric_trend",
        chart_types=["time_series", "line"],
        output_sections=["trend", "change", "anomalies"],
        tags=["trend", "metric"],
    ),
    AnalysisPlaybook(
        playbook_id="period_comparison",
        display_name="周期对比分析",
        description="比较两个日期区间的指标绝对变化、相对变化和主要维度贡献。",
        supported_goal_modes=["metric_diagnosis", "growth_trend", "periodic_report"],
        requirements=PlaybookRequirements(requires_date_column=True, requires_metric_columns=True),
        parameters=[
            _parameter("comparison_type", "对比方式", "choice", default="previous_period", choices=["previous_period", "custom"]),
            _parameter("current_start", "当前周期开始", "date"),
            _parameter("current_end", "当前周期结束", "date"),
            _parameter("previous_start", "对比周期开始", "date"),
            _parameter("previous_end", "对比周期结束", "date"),
            _parameter("top_n", "Top N", "integer", default=10),
            _parameter("aggregation", "聚合方式", "choice", default="sum", choices=["sum", "mean", "count", "min", "max"]),
        ],
        executor_name="execute_period_comparison",
        chart_types=["grouped_bar", "contribution_bar"],
        output_sections=["comparison", "change", "dimensions"],
        tags=["comparison", "period"],
    ),
    AnalysisPlaybook(
        playbook_id="dimension_contribution",
        display_name="维度贡献分析",
        description="按所选维度拆解指标，输出贡献值、贡献占比、排名及 Others。",
        supported_goal_modes=["metric_diagnosis", "content_performance", "live_quality", "periodic_report"],
        requirements=PlaybookRequirements(requires_metric_columns=True, requires_dimension_columns=True),
        parameters=[
            _parameter("metric", "指标", "column"),
            _parameter("dimension", "维度", "column"),
            _parameter("top_n", "Top N", "integer", default=10),
            _parameter("sort_order", "排序", "choice", default="descending", choices=["descending", "ascending"]),
            _parameter("include_others", "合并 Others", "boolean", default=True),
            _parameter("aggregation", "聚合方式", "choice", default="sum", choices=["sum", "mean", "count", "min", "max"]),
        ],
        executor_name="execute_dimension_contribution",
        chart_types=["contribution_bar", "table"],
        output_sections=["ranking", "contribution"],
        tags=["dimension", "attribution"],
    ),
    AnalysisPlaybook(
        playbook_id="experiment_comparison",
        display_name="实验组对照组比较",
        description="比较对照组与实验组的均值或比例，输出 lift、p-value 与置信区间。",
        supported_goal_modes=["experiment_analysis"],
        requirements=PlaybookRequirements(requires_group_column=True, requires_metric_columns=True, minimum_rows=4),
        parameters=[
            _parameter("control_value", "对照组值", "string", default="control"),
            _parameter("treatment_value", "实验组值", "string", default="treatment"),
            _parameter("metric", "指标", "column"),
            _parameter("metric_type", "指标类型", "choice", default="mean", choices=["mean", "proportion"]),
            _parameter("confidence_level", "置信水平", "float", default=0.95),
            _parameter("dimension", "分层维度", "column"),
        ],
        executor_name="execute_experiment_comparison",
        chart_types=["grouped_bar", "confidence_interval"],
        output_sections=["experiment", "significance", "confidence_interval"],
        tags=["experiment", "comparison"],
    ),
    AnalysisPlaybook(
        playbook_id="causal_exploration",
        display_name="轻量因果探索",
        description="输出 naive difference、回归调整结果和明确的适用边界。",
        supported_goal_modes=["causal_exploration"],
        requirements=PlaybookRequirements(requires_treatment_column=True, requires_outcome_column=True, minimum_rows=10),
        parameters=[
            _parameter("covariates", "控制变量", "dimension_columns", default=[]),
            _parameter("treatment_value", "处理组值", "string", default="treatment"),
            _parameter("control_value", "对照组值", "string", default="control"),
        ],
        executor_name="execute_causal_exploration",
        chart_types=["bar"],
        output_sections=["naive", "adjusted", "caveats"],
        tags=["causal", "exploration"],
    ),
    AnalysisPlaybook(
        playbook_id="periodic_summary",
        display_name="周期分析摘要",
        description="组合数据概览、趋势、周期变化和主要维度，生成一页式摘要。",
        supported_goal_modes=["periodic_report", "growth_trend", "metric_diagnosis"],
        requirements=PlaybookRequirements(requires_table=True),
        parameters=[
            _parameter("time_grain", "时间粒度", "choice", default="day", choices=["day", "week", "month"]),
            _parameter("aggregation", "聚合方式", "choice", default="sum", choices=["sum", "mean", "count", "min", "max"]),
            _parameter("rolling_window", "滚动窗口", "integer", default=7),
            _parameter("top_n", "Top N", "integer", default=5),
        ],
        executor_name="execute_periodic_summary",
        chart_types=["metric_card", "time_series", "contribution_bar"],
        output_sections=["profile", "trend", "comparison", "top_dimensions"],
        tags=["periodic", "summary"],
    ),
    AnalysisPlaybook(
        playbook_id="semantic_metric_query",
        display_name="语义指标查询",
        description="基于受控语义模型编译指标、维度、筛选和多表连接，并生成可审批的只读查询计划。",
        supported_goal_modes=["metric_diagnosis", "growth_trend", "periodic_report"],
        requirements=PlaybookRequirements(
            requires_table=False,
            required_tables=["customers", "sessions", "orders", "order_items", "products", "channels", "calendar"],
            requires_semantic_model=True,
        ),
        parameters=[
            _parameter("semantic_model_id", "语义模型", "string", default="commerce_demo", description="选择已注册且通过校验的本地语义模型。"),
            _parameter("metric", "语义指标", "metric", default="total_revenue", description="从语义模型中选择一个已定义指标。"),
            _parameter("dimensions", "分析维度", "dimensions", default=["order_date"], description="选择一个或多个受控语义维度。"),
            _parameter("date_dimension", "日期维度", "string", default="order_date", description="用于日期范围和时间粒度的语义日期维度。"),
            _parameter("date_from", "开始日期", "date", description="可选的查询开始日期。"),
            _parameter("date_to", "结束日期", "date", description="可选的查询结束日期。"),
            _parameter("time_grain", "时间粒度", "choice", default="day", choices=["day", "week", "month"], description="日期维度聚合粒度。"),
            _parameter("execution_mode", "执行模式", "choice", default="execute", choices=["plan_only", "execute"], description="仅预览方案或执行已通过安全检查的只读查询。"),
            _parameter("approved_plan_id", "已批准计划编号", "string", description="高风险计划必须提供与当前计划一致的批准编号。"),
            _parameter("limit", "结果行数上限", "integer", default=1000, description="结果最多返回 10000 行。"),
        ],
        executor_name="execute_semantic_metric_query",
        chart_types=["time_series", "bar", "table"],
        output_sections=["semantic_model", "join_plan", "query_plan", "metric_result"],
        tags=["semantic", "metric", "multi_table"],
        field_requirements_zh=["语义模型中的指标", "可选语义维度", "模型声明的实体关系"],
        result_description_zh="输出中文查询计划摘要、连接风险、审批状态和指标结果表。",
        caveats_zh=["语义指标口径仅适用于当前内置模拟模型。", "高风险连接未经匹配审批不会执行。"],
    ),
    AnalysisPlaybook(
        playbook_id="funnel_analysis",
        display_name="漏斗转化分析",
        description="按照访问、浏览商品、加入购物车、提交订单和支付完成计算本地模拟漏斗。",
        supported_goal_modes=["growth_trend", "periodic_report", "content_performance"],
        requirements=PlaybookRequirements(requires_table=False, required_tables=["sessions"]),
        parameters=[
            _parameter("date_from", "开始日期", "date", description="可选的会话开始日期。"),
            _parameter("date_to", "结束日期", "date", description="可选的会话结束日期。"),
        ],
        executor_name="execute_funnel_analysis",
        chart_types=["bar", "table"],
        output_sections=["funnel", "conversion", "caveats"],
        tags=["funnel", "multi_table"],
        field_requirements_zh=["sessions 表", "五个 0/1 漏斗阶段字段", "可选会话日期字段"],
        result_description_zh="输出各阶段人数、相对上一步转化率和相对访问转化率。",
        caveats_zh=["漏斗仅反映内置模拟会话事件，不代表真实行为。"],
    ),
    AnalysisPlaybook(
        playbook_id="cohort_retention",
        display_name="队列留存分析",
        description="使用客户注册日期和后续会话日期计算按周队列留存。",
        supported_goal_modes=["growth_trend", "periodic_report"],
        requirements=PlaybookRequirements(requires_table=False, required_tables=["customers", "sessions"]),
        parameters=[
            _parameter("observation_periods", "观察周期数", "integer", default=8, description="从首周开始保留的观察周期数量，范围 1 到 26。"),
        ],
        executor_name="execute_cohort_retention",
        chart_types=["line", "table"],
        output_sections=["cohort", "retention", "caveats"],
        tags=["cohort", "retention", "multi_table"],
        field_requirements_zh=["customers.customer_id", "customers.signup_date", "sessions.customer_id", "sessions.session_date"],
        result_description_zh="输出队列日期、队列人数、观察周期、留存人数和留存率。",
        caveats_zh=["观察窗口末端的较新队列可能尚未拥有完整留存周期。"],
    ),
]


def get_builtin_playbooks() -> list[AnalysisPlaybook]:
    return list(BUILTIN_PLAYBOOKS)
